### ISSUE TITLE
Support for recent versions of GHC?

### ISSUE THREAD

**Issue by peti** [frerich/catamorphism#5]
Hi,

I would love to use this great package, but unfortunately the build fails with GHC 8.0.2, because of the following unsatisfyable constraints:

    base >=4.6 && <4.9, template-haskell >=2.8 && <2.11

I suppose similar issues would exist with GHC 8.2.1. 

Would it be possible to get an updated version of this package that remedies this issue, i.e. by means of http://hackage.haskell.org/package/th-abstraction?

Best regards,
Peter

**Comment by frerich** [comment]
I'd certainly like to make this package work with recent GHC versions.

On first glance, doing this seemed to be straightforward: the `DataD` and `NewtypeD` constructors take a sixth argument in template-haskell 2.11.0.0, so one would need a patch along the lines of
```diff
@@ -142,8 +146,8 @@ makeCata :: CataOptions     -- Options to customize the catamorphism; the name o
 makeCata opts ty = do
     typeInfo <- reify ty
     (tyVarBndrs, cons) <- case typeInfo of
-            TyConI (DataD _ _ tyVarBndrs cons _)   -> return (tyVarBndrs, cons)
-            TyConI (NewtypeD _ _ tyVarBndrs con _) -> return (tyVarBndrs, [con])
+            TyConI (DataD _ _ tyVarBndrs _ cons _)   -> return (tyVarBndrs, cons)
+            TyConI (NewtypeD _ _ tyVarBndrs _ con _) -> return (tyVarBndrs, [con])
             _                                      -> fail "makeCata: Expected name of type constructor"
     sequence [signature tyVarBndrs cons, funDef cons]
   where
```

However, it also turned out that two new constructors `GadtC` and `RecGadtC` were added to `Con`. It's not clear to me yet what this means for the `catamorphism` package; the `conArgTypes` definition could be extended like

```diff
@@ -113,12 +113,16 @@ conArgTypes (NormalC _ args)     = map snd args
 conArgTypes (RecC _ args)        = map (\(_,_,x) -> x) args
 conArgTypes (InfixC arg1 _ arg2) = map snd [arg1, arg2]
 conArgTypes (ForallC _ _ c)      = conArgTypes c
+conArgTypes (GadtC _ args _)     = map snd args
+conArgTypes (RecGadtC _ args _)  = map (\(_,_,x) -> x) args
...
```

...but what to do about `conName :: Con -> Name`? Both `GadtC` as well as `RecGadtC` take a [list of `Name` values](http://hackage.haskell.org/package/template-haskell-2.12.0.0/docs/Language-Haskell-TH-Syntax.html#t:Con). Which of them (if any) to pick? Maybe we should simply disallow usage with GADTs? I'll need to think about this.

**Comment by peti** [comment]
@frerich, have you made any progress with this issue? Meanwhile, GHC 8.2.2 has arrived on the scene and it would be really nice to be able to use this library in code that requires a recent compiler!

**Comment by frerich** [comment]
@peti I must admit that I didn't continue working on this, no (and I do feel fairly guilty about it). :-/

**Comment by peti** [comment]
If it's any help ... I think that a solution that works for *some* cases is pretty useful already. If GADTs are tricky to get right, then it's just fine to omit them IMHO.

**Comment by peti** [comment]
Ping?

**Comment by peti** [comment]
Thank you!
